@component('mail::message')

This message was generated by using laravels "Artisan make:mail --markdown"

@component('mail::button', ['url' => '/'])
Visit my page!
@endcomponent

@component('mail::panel',['url'=>'test'])
Panel Component test
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent
